[package]
name = "fyodor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
integer-encoding = "3.0.3"
thiserror = "1.0"
rand = "0.8.5"
crossbeam = "0.8.2"